<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MemoaLibraryTargetFrameworks)</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <Description>REST API endpoints for replaying HTTP requests captured by Memoa middleware.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Memoa.Core\Memoa.Core.csproj" />
    <ProjectReference Include="..\Memoa.Replay.Core\Memoa.Replay.Core.csproj" />
  </ItemGroup>

</Project>
