<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Memoa.Sinks.Redis\Memoa.Sinks.Redis.csproj" />
  </ItemGroup>

</Project>
