<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Memoa.Core\Memoa.Core.csproj" />
  </ItemGroup>

</Project>
