<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Memoa.Sinks.AzureBlobStorage\Memoa.Sinks.AzureBlobStorage.csproj" />
  </ItemGroup>

</Project>
